version: '2'
services:
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: nginx.dockerfile
    labels:
      lagoon.type: nginx
      lagoon.volumes.persist.path: /app/public/storage
    volumes:
      - ./public:/app:delegated

volumes:
  persist:
    labels:
      lagoon.type: persistent

networks:
  amazeeio-network:
    external: true
